// Terms of Service

import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
            {/* Header */}
            <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex items-center justify-between h-16">
                        <Link
                            href="/"
                            className="flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
                        >
                            <ArrowLeft className="w-5 h-5" />
                            Back to Home
                        </Link>
                        <div className="flex items-center gap-2">
                            <Sparkles className="w-5 h-5 text-indigo-600" />
                            <span className="font-semibold text-gray-900 dark:text-white">Nexus Insights</span>
                        </div>
                    </div>
                </div>
            </header>

            <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div className="bg-white dark:bg-gray-800 rounded-2xl p-8 border border-gray-200 dark:border-gray-700">
                    <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">
                        Terms of Service
                    </h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">
                        Last updated: February 2026
                    </p>

                    <div className="prose dark:prose-invert max-w-none">
                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using Nexus Insights, you agree to be bound by these Terms of Service
                            and our Privacy Policy. If you do not agree to these terms, please do not use our service.
                        </p>

                        <h2>2. Description of Service</h2>
                        <p>
                            Nexus Insights provides AI-powered analysis of YouTube video comments to extract
                            product intelligence, sentiment analysis, and actionable insights. We use the YouTube
                            Data API v3 to access publicly available comment data.
                        </p>

                        <h2>3. User Responsibilities</h2>
                        <p>You agree to:</p>
                        <ul>
                            <li>Provide accurate information when creating an account</li>
                            <li>Use the service only for lawful purposes</li>
                            <li>Not attempt to circumvent any security measures</li>
                            <li>Not use the service to harass, abuse, or harm others</li>
                            <li>Comply with YouTube&apos;s Terms of Service and Community Guidelines</li>
                        </ul>

                        <h2>4. Intellectual Property</h2>
                        <p>
                            The analysis, insights, and recommendations generated by Nexus Insights are provided
                            for your use. YouTube comment content remains the property of its original authors.
                            Our AI models, algorithms, and platform design are our intellectual property.
                        </p>

                        <h2>5. Limitations</h2>
                        <p>
                            Our analysis is based on publicly available YouTube comments and AI interpretation.
                            We do not guarantee the accuracy of insights or recommendations. Use your judgment
                            when making business decisions based on our analysis.
                        </p>

                        <h2>6. Pricing and Billing</h2>
                        <p>
                            Free tier users receive limited analyses per month. Paid subscriptions are billed
                            monthly or annually. Refunds are provided according to our refund policy.
                        </p>

                        <h2>7. Service Availability</h2>
                        <p>
                            We strive to maintain high availability but do not guarantee uninterrupted service.
                            We may perform maintenance or updates that temporarily affect availability.
                        </p>

                        <h2>8. Termination</h2>
                        <p>
                            We reserve the right to suspend or terminate accounts that violate these terms or
                            engage in abusive behavior. You may cancel your account at any time.
                        </p>

                        <h2>9. Changes to Terms</h2>
                        <p>
                            We may update these terms from time to time. We will notify users of significant
                            changes via email or in-app notification.
                        </p>

                        <h2>10. Contact</h2>
                        <p>
                            For questions about these Terms of Service, please contact us at legal@nexusinsights.com.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}
